### ISSUE TITLE
 Character not found

### ISSUE THREAD

**Issue by jervo** [GeekyEggo/DestinyTailor#6]
Great program; however, it looks like access to guardians accounts is being denied after todays bungie maintenance/update.I tried my PS4 and XBox accounts both get "Character not found" error 8-(

**Comment by GeekyEggo** [comment]
Hey @jervo, thanks for letting me know! It looks like the Bungie.net API has been throwing errors on the `GetAccountSummary` endpoint since yesterday, with the error `The account you are trying to access has has fallen into disrepair. Playing the game again will usually clear things up.`.

There's a [post on the "BungieNetPlatform"](https://www.bungie.net/en/Clan/Post/39966/206239994/0/0) group on Bungie.net, so I'll track that and post an update / fix when I possible.

**Comment by jervo** [comment]
@GeekyEggo Thanks for quick response. I just checked after bungie's latest "return" from maintenance and your program is running like a charm again! Thanks!
